---
abstract: 'Provides a Document and Page for PDF files.'
author:
  - 'Project Renard'
build_requires:
  Renard::Incunabula::Devel::TestHelper: '0'
  Test::Most: '0'
  lib: '0'
  perl: '5.010'
configure_requires:
  ExtUtils::MakeMaker: '0'
  perl: '5.010'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Renard-Incunabula-Format-PDF
requires:
  Cairo: '0'
  Function::Parameters: '0'
  Math::Polygon: '0'
  Math::Trig: '0'
  Moo: '0'
  MooX::HandlesVia: '0'
  POSIX: '0'
  Renard::Incunabula::Common::Setup: '0'
  Renard::Incunabula::Common::Types: '0'
  Renard::Incunabula::Document: '0'
  Renard::Incunabula::MuPDF::mutool: '0'
  Renard::Incunabula::Outline: '0'
  perl: '5.010'
resources:
  homepage: https://github.com/project-renard/p5-Renard-Incunabula-Format-PDF
  repository: https://github.com/project-renard/p5-Renard-Incunabula-Format-PDF.git
version: '0.003'
x_serialization_backend: 'YAML::Tiny version 1.70'
